name: build

on: [push, pull_request]

jobs:
  install-macos:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install project
        run: ./scripts/install.sh
  install-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install project
        run: ./scripts/install.sh
